### ISSUE TITLE
Portainer: "Deployment error unsupported Compose file version: 2" 

### ISSUE THREAD

**Issue by Ziimmie** [bnhf/pivpn-tap-web-ui#1]
Hello,

I was trying to deploy this with Portainer. I copied the stack configuration from the one in the readme, but Portainer gives me a unsupported Compose file version. If it helps, I am on Portainer 2.11.1 on Ubuntu Server 21.04 LTS.

**Comment by bnhf** [comment]
Sounds like you're copying the .yml contents into the Portainer Stack editor, which is fine. I don't think it would be a problem to change the Compose version number to say 3.3 -- if you're setup isn't backward compatible to 2. Also, if you're not already, you might try using the Github option in Portainer - Stacks where you reference the .yml in the repo, and add your specific environment variables. Let me know how it works out. :-)

**Comment by bnhf** [comment]
Jack - One other thing: I just looked at my running version of the container, and I'm also on Portainer 2.11.1, but am using Debian 11. I deployed via the git repository method, with my set of environment variables added.

Looks like this:
![screenshot-nuc10-pc2-2022 04 22-14_48_34](https://user-images.githubusercontent.com/41088895/164791956-5ef101eb-bda8-4fdb-848e-3ddd0677b574.png)

Let me know if you think anything else needs clarification. I spent quite a bit of time on development of this project, but haven't gotten much feedback so far. Thanks, Scott

**Comment by Ziimmie** [comment]
Hey Scott - I forked the repo and changed the version to 3.3 and now the stack created successfully. Now just figuring out how to get this setup - I'm new to this :). I have to do some digging because port 8080 is refusing to connect right now, but thank you for all your help!

**Comment by bnhf** [comment]
Ubuntu Server has firewall enabled by default I believe, so you'd need to open the port. If you have a conflict with something else on the host using 8080, you can remap it in your fork (and redeploy the container). Whatever port you want to map it to on the host goes first, so if it was 8081 you'd change 8080:8080 to 8081:8080 in the .yml.
