### ISSUE TITLE
SERVER TIME

### ISSUE THREAD

**Issue by karabelnikov** [bnhf/pivpn-tap-web-ui#6]
@bnhf

Greetings! I discovered an interesting feature. The monitoring page displays the time in UTC format, regardless of the time zone and time on the server. The time on my server is taking into account GMT+05, but it stubbornly shows UTC on the monitoring page. How do I achieve that the time on the server shows taking into account my time zone or server time?

![Снимок экрана 2022-12-05 в 12 36 49](https://user-images.githubusercontent.com/11692792/205580306-ad2fa883-5de3-435d-ba68-c8a745d9cc17.png)

**Comment by bnhf** [comment]
@karabelnikov 

If you used the Github method for creating your stack described in the README, then add a TZ environment variable, along with the appropriate timezone as the value, and redeploy. If you've created the stack locally using a custom compose, then add a ```- TZ=``` followed by your timezone. Final option is to add ```TZ=${TZ}``` to your custom compose and then add the environment variable as described in the first sentence above.
