### ISSUE TITLE
Fix your configuration ERROR

### ISSUE THREAD

**Issue by jrosetto** [bnhf/pivpn-tap-web-ui#73]
Have everything working properly on Ubuntu Server 24.04 except seeing who is connected.

Client count shows MAPPING ERROR and connected clients shows Fix your configuration.

Can you give some pointers on what to look at to get this working?

If you need more info from me feel free to reach out.

Thanks.

Also just noticed the log page is empty

**Comment by bnhf** [comment]
> Client count shows MAPPING ERROR and connected clients shows Fix your configuration.

@jrosetto 

This typically means you haven't run through the initial configuration step of inputting your values into _Configuration - OpenVPN config_. I think sometimes people think they don't need to do this, as their OpenVPN Server is already running -- however it is required. This sets up the OpenVPN Management Interface as well as the logs. Do this first, restart OpenVPN Server, and then you can make your specific changes to _Configuration - Settings_.

**Comment by jrosetto** [comment]
> > Client count shows MAPPING ERROR and connected clients shows Fix your configuration.
> 
> @jrosetto
> 
> This typically means you haven't run through the initial configuration step of inputting your values into _Configuration - OpenVPN config_. I think sometimes people think they don't need to do this, as their OpenVPN Server is already running -- however it is required. This sets up the OpenVPN Management Interface as well as the logs. Do this first, restart OpenVPN Server, and then you can make your specific changes to _Configuration - Settings_.

I think where I went off the rails was when I configured OpenVPN Server as tun instead of tap.

For the fun of it I moved the server back to tap0 and configured OpenVPN GUI v2 client and everything shows as I expect.

Unfortunately OpenVPN Connect v3 Client does not support tap and only works across tun.
Is there a way for me to get this gui working with tun?

**Comment by bnhf** [comment]
> Is there a way for me to get this gui working with tun?

@jrosetto 

It definitely works with tun and tap, and I use it for both. Can you post your desired OpenVPN tun config, as shown in the WebUI or server.conf file? Your port number is probably the only thing you'd need to redact.

**Comment by jrosetto** [comment]
> > Is there a way for me to get this gui working with tun?
> 
> @jrosetto
> 
> It definitely works with tun and tap, and I use it for both. Can you post your desired OpenVPN tun config, as shown in the WebUI or server.conf file? Your port number is probably the only thing you'd need to redact.

Thank you for pointing me in the right direction.  I haven't used OVPN in quite some time and am rusty at configuring.  Everything is working as intended now.  Frontend looks great, good job :)
